### ISSUE TITLE
Typing in YouTube and pressing Enter key causes the entire text box to clear in Firefox

### ISSUE THREAD

**Issue by jinwk00** [fcitx/fcitx5-hangul#2]
Every time when I type any Korean word, such as "리눅스" in some websites such as YouTube, when the last letter "**스**" is being selected and if I press the Enter/Return key, the entire text box causes to disappear. 

The only way to remediate this is to press the Right arrow key or click on the text box to 'unselect' the last letter, then I am able to press Enter without any issues.

Currently running Arch Linux under KDE Plasma X11, Firefox installed from Arch extra repository. Same thing happens even if I use Firefox from Flatpak.

**Comment by wengxt** [comment]
yeah, flatpak firefox is using new fcitx5-gtk now . as for the runtime you'll need to wait for the freedesktop runtime to pickup the next fcitx5-gtk update. mean while, if you can't upgrade it, you can also type an extra space before you do the search, I think that can some how workaround it.
