### ISSUE TITLE
Is there a way to add hanja(漢字) words?

### ISSUE THREAD

**Issue by nemonein** [fcitx/fcitx5-hangul#6]
Hello.
I'd like to adds some 漢字 words to fcitx-hangul.
For example, input '범용' and press `F9`, and it shows some candidates for '범용', but 汎用 is not in it.

Is it possible?

**Comment by wengxt** [comment]
It's possible to provide with a user level file at ~/.local/share/libhangul/hanja/hanja.txt . You can make a copy of /usr/share/libhangul/hanja/hanja.txt and then add your new entries.

**Comment by nemonein** [comment]
Thanks!! It works fine.
