### ISSUE TITLE
hangul input issue when "Caps Lock" is activated

### ISSUE THREAD

**Issue by hansm629** [fcitx/fcitx5-hangul#9]
With `Caps Lock` enabled
When typing hangul

It is being typed as if the `Shift` key was pressed at the same time.

ex:
**Disable Caps Lock**
```
ㅂㅈㄷㄱㅅㅔㅔ
``` 

**Enable Caps Lock**
```
ㅃㅉㄸㄲㅆㅒㅖ
```

Only when the `Shift` key is pressed simultaneously
Can you fix it so that it is entered as `ㅃㅉㄸㄲㅆㅒㅖ`?

**Comment by hansm629** [comment]
@wengxt 
Thanks for fixing it. :)

It seems that it is currently only committed to the master branch. When will it be reflected in the official version?

Will this be reflected in version 5.1.4 or so?

**Comment by wengxt** [comment]
@hansm629 we do new release on the latest commit. So it will be in next release.

As for when the release will happen, I plan to do a new release soon this week, after finishing some other work on other engines since we do cut on all repos at the same time.
